// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWQWS1kV1J3ICHeF4jVGE3yeN4bSXtAMc',
    appId: '1:498260518748:web:3e6842b569ffe677308399',
    messagingSenderId: '498260518748',
    projectId: 'anonymous-chat-ad771',
    authDomain: 'anonymous-chat-ad771.firebaseapp.com',
    storageBucket: 'anonymous-chat-ad771.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB6KgmBWayfODTOCAEb6YdGYCaSdBiCrc',
    appId: '1:498260518748:android:4977b2840fb77024308399',
    messagingSenderId: '498260518748',
    projectId: 'anonymous-chat-ad771',
    storageBucket: 'anonymous-chat-ad771.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxh37Fm7PFOS8b0VcUWcO3nqCDKUeiLzQ',
    appId: '1:498260518748:ios:5c10fad212edd97b308399',
    messagingSenderId: '498260518748',
    projectId: 'anonymous-chat-ad771',
    storageBucket: 'anonymous-chat-ad771.appspot.com',
    iosClientId: '498260518748-r5i4vtv4h8n8nee21e7redcqtn60ra57.apps.googleusercontent.com',
    iosBundleId: 'com.example.anonymousChat',
  );
}
